# Generated by Django 5.0.6 on 2024-06-27 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('patty_one', models.CharField(choices=[('Burger', 'Burger'), ('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Ground Beef', 'Ground Beef'), ('Ground Ribs', 'Ribs')], default='Burger', max_length=100)),
                ('patty_two', models.CharField(choices=[('Burger', 'Burger'), ('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Ground Beef', 'Ground Beef'), ('Ground Ribs', 'Ribs')], default=None, max_length=100, null=True)),
                ('patty_three', models.CharField(choices=[('Burger', 'Burger'), ('Chicken', 'Chicken'), ('Fish', 'Fish'), ('Ground Beef', 'Ground Beef'), ('Ground Ribs', 'Ribs')], default=None, max_length=100, null=True)),
                ('cheese_one', models.CharField(choices=[('American Cheese', 'American'), ('Cheddar', 'Cheddar'), ('Pepper Jack', 'Pepper'), ('Monterey Jack', 'Monterey'), ('Provolone', 'Provolone')], default='American Cheese', max_length=100)),
                ('cheese_two', models.CharField(choices=[('American Cheese', 'American'), ('Cheddar', 'Cheddar'), ('Pepper Jack', 'Pepper'), ('Monterey Jack', 'Monterey'), ('Provolone', 'Provolone')], default=None, max_length=100, null=True)),
                ('cheese_three', models.CharField(choices=[('American Cheese', 'American'), ('Cheddar', 'Cheddar'), ('Pepper Jack', 'Pepper'), ('Monterey Jack', 'Monterey'), ('Provolone', 'Provolone')], default=None, max_length=100, null=True)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large')], default='Regular', max_length=100)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='burgers', to='orders.order')),
            ],
        ),
    ]
