# Generated by Django 4.1.13 on 2024-07-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burger',
            name='order',
        ),
    ]
