# Generated by Django 5.0.6 on 2024-06-27 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.TextField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('description', models.TextField(blank=True)),
                ('meat_one', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Ground Meat', 'Ground Meat'), ('Italian Sausage', 'Italian Sausage'), ('Chicken', 'Chicken'), ('Ham', 'Ham')], default='Pepperoni', max_length=100)),
                ('meat_two', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Ground Meat', 'Ground Meat'), ('Italian Sausage', 'Italian Sausage'), ('Chicken', 'Chicken'), ('Ham', 'Ham')], default=None, max_length=100, null=True)),
                ('meat_three', models.CharField(choices=[('Pepperoni', 'Pepperoni'), ('Ground Meat', 'Ground Meat'), ('Italian Sausage', 'Italian Sausage'), ('Chicken', 'Chicken'), ('Ham', 'Ham')], default=None, max_length=100, null=True)),
                ('cheese_one', models.CharField(choices=[('Mozzarela', 'Mozzarela'), ('Provolone', 'Provolone'), ('Cheddar', 'Cheddar'), ('Parmesan', 'Parmesan'), ('Asiago', 'Asiago')], default='Mozzarela', max_length=100)),
                ('cheese_two', models.CharField(choices=[('Mozzarela', 'Mozzarela'), ('Provolone', 'Provolone'), ('Cheddar', 'Cheddar'), ('Parmesan', 'Parmesan'), ('Asiago', 'Asiago')], default=None, max_length=100, null=True)),
                ('cheese_three', models.CharField(choices=[('Mozzarela', 'Mozzarela'), ('Provolone', 'Provolone'), ('Cheddar', 'Cheddar'), ('Parmesan', 'Parmesan'), ('Asiago', 'Asiago')], default=None, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large')], default='Regular', max_length=100)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.order')),
            ],
        ),
    ]
