# Generated by Django 5.0.6 on 2024-06-27 13:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('flavor', models.CharField(choices=[('Cola', 'Cola'), ('Lemon', 'Lemon'), ('Grape', 'Grape'), ('Strawberry', 'Strawberry'), ('Cherry', 'Cherry')], default='Cola', max_length=100)),
                ('drink_type', models.CharField(choices=[('Soda', 'Soda'), ('Juice', 'Juice'), ('Iced Tea', 'Tea'), ('Iced Coffee', 'Coffee'), ('Smoothie', 'Smoothie')], default='Soda', max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large')], default='Regular', max_length=100)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drinks', to='orders.order')),
            ],
        ),
    ]
