# Generated by Django 3.2.25 on 2024-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_drink_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
