# Generated by Django 5.0.6 on 2024-06-27 16:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.TextField()),
                ('flavor', models.CharField(choices=[('Savory', 'Savory'), ('Sweet', 'Sweet')], default='Savory', max_length=100)),
                ('prepare', models.CharField(choices=[('Fried', 'Fried'), ('Cooked', 'Cooked'), ('Cooled', 'Cooled'), ('Grilled', 'Grilled'), ('Natural', 'Natural')], default='Fried', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('description', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Regular', 'Regular'), ('Large', 'Large')], default='Regular', max_length=100)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snacks', to='orders.order')),
            ],
        ),
    ]
