# Generated by Django 5.0.6 on 2024-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_alter_snack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='prepare',
            field=models.CharField(choices=[('Fried', 'Fried'), ('Cooked', 'Cooked'), ('Freezed', 'Freezed'), ('Grilled', 'Grilled'), ('Natural', 'Natural'), ('Baked', 'Baked')], default='Fried', max_length=100),
        ),
    ]
