# Generated by Django 4.1.13 on 2024-07-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_alter_snack_prepare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='order',
        ),
    ]
