# Generated by Django 4.1.13 on 2024-07-02 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0004_remove_snack_order'),
        ('burgers', '0002_remove_burger_order'),
        ('pizzas', '0002_remove_pizza_order'),
        ('drinks', '0002_remove_drink_order'),
        ('orders', '0002_order_order_updated_order_ordered_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='burgers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burgers.burger'),
        ),
        migrations.AddField(
            model_name='order',
            name='drinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drinks.drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizzas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='snacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snacks.snack'),
        ),
    ]
