# Generated by Django 4.1.13 on 2024-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_remove_drink_order'),
        ('pizzas', '0002_remove_pizza_order'),
        ('snacks', '0004_remove_snack_order'),
        ('burgers', '0002_remove_burger_order'),
        ('orders', '0008_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='burger',
            field=models.ManyToManyField(related_name='orders', to='burgers.burger'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(related_name='orders', to='drinks.drink'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(related_name='orders', to='pizzas.pizza'),
        ),
        migrations.AlterField(
            model_name='order',
            name='snack',
            field=models.ManyToManyField(related_name='orders', to='snacks.snack'),
        ),
    ]
