# Generated by Django 3.2.25 on 2024-07-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_burger_alter_order_drink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=200),
        ),
    ]
